DROP TABLE IF EXISTS studios, films CASCADE;


CREATE TABLE studios (

id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name TEXT NOT NULL,
city TEXT NOT NULL,
state TEXT NULL,
country TEXT NOT NULL

);


CREATE TABLE films (

id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
title TEXT NOT NULL,
studio BIGINT NOT NULL REFERENCES studios(id),
release DATE NOT NULL

);

